stages:
  - build
  - test
  - quality

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/
    - .npm/

# =========================
# BACKEND - SPRING BOOT
# =========================

backend_test:
  stage: test
  image: maven:3.9-eclipse-temurin-17

  script:
    - cd mdx_store
    - mvn -Dmaven.repo.local="$CI_PROJECT_DIR/.m2/repository" test


backend_build:
  stage: build
  image: maven:3.9-eclipse-temurin-17

  script:
    - cd mdx_store
    - mvn -Dmaven.repo.local="$CI_PROJECT_DIR/.m2/repository" clean package -DskipTests

  artifacts:
    paths:
      - mdx_store/target/*.jar
    expire_in: 1 week

# =========================
# FRONTEND
# =========================

frontend_test:
  stage: test
  image: node:20

  script:
    - cd sawa-jewelry
    - npm ci --cache "$CI_PROJECT_DIR/.npm"
    - npm run lint


frontend_build:
  stage: build
  image: node:20

  script:
    - cd sawa-jewelry
    - npm ci --cache "$CI_PROJECT_DIR/.npm"
    - npm run build

  artifacts:
    paths:
      - sawa-jewelry/.next/
    expire_in: 1 week

# =========================
# SONARQUBE
# =========================

backend_sonarqube:
  stage: quality
  image: maven:3.9-eclipse-temurin-17
  needs:
    - backend_test
  script:
    - cd mdx_store
    - mvn -Dmaven.repo.local="$CI_PROJECT_DIR/.m2/repository" clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey="$SONAR_BACKEND_PROJECT_KEY" -Dsonar.organization="$SONAR_ORGANIZATION" -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.token="$SONAR_TOKEN" -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.qualitygate.wait=true
  rules:
    - if: '$SONAR_HOST_URL && $SONAR_TOKEN && $SONAR_ORGANIZATION && $SONAR_BACKEND_PROJECT_KEY'

frontend_sonarqube:
  stage: quality
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  needs:
    - frontend_test
  script:
    - cd sawa-jewelry
    - sonar-scanner -Dsonar.projectKey="$SONAR_FRONTEND_PROJECT_KEY" -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.organization="$SONAR_ORGANIZATION" -Dsonar.token="$SONAR_FRONTEND_TOKEN" -Dsonar.qualitygate.wait=true
  rules:
    - if: '$SONAR_HOST_URL && $SONAR_FRONTEND_TOKEN && $SONAR_ORGANIZATION && $SONAR_FRONTEND_PROJECT_KEY'