stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/
    - .npm/

# =========================
# BACKEND - SPRING BOOT
# =========================

backend_test:
  stage: test
  image: maven:3.9-eclipse-temurin-17

  script:
    - cd mdx_store
    - mvn -Dmaven.repo.local="$CI_PROJECT_DIR/.m2/repository" test


backend_build:
  stage: build
  image: maven:3.9-eclipse-temurin-17

  script:
    - cd mdx_store
    - mvn -Dmaven.repo.local="$CI_PROJECT_DIR/.m2/repository" clean package -DskipTests

  artifacts:
    paths:
      - mdx_store/target/*.jar
    expire_in: 1 week

# =========================
# FRONTEND
# =========================

frontend_test:
  stage: test
  image: node:20

  script:
    - cd sawa-jewelry
    - npm ci --cache "$CI_PROJECT_DIR/.npm"
    - npm run lint


frontend_build:
  stage: build
  image: node:20

  script:
    - cd sawa-jewelry
    - npm ci --cache "$CI_PROJECT_DIR/.npm"
    - npm run build

  artifacts:
    paths:
      - sawa-jewelry/.next/
    expire_in: 1 week